about.md
Some minor prose tweaks for readability
=> About Page

_data/members.yml, _posts/2015-03-24-why-we-run-an-open-source-program-twitter.md
First cut of the Twitter post for this series
I'll probably make sure edits to this tomorrow for sanity purposes @jamesgpearce but wanted to make sure you knew it was in queue. We should work with Gianugo to get this post queued next
=> Initial draft of the Twitter post

_includes/footer.html, _includes/header.html, _sass/forms.scss, static/style.scss
The code of conduct links to the styles here, and I had to make some tweaks to support https://github.com/todogroup/opencodeofconduct/pull/10
Notable changes:
- Extract a `.container` class
- Make form styles reusable
/cc @amateurhuman
=> Tweaks for code of conduct

_posts/2015-07-15-creating-an-open-source-office-box.md
Thanks @asheepapart, let me know if this works for you.
Signed-off-by: Chris Aniszczyk <zx@twitter.com>
=> Add "Creating an Open Source Office at Box"

_data/members.yml, _posts/2015-07-20-open-code-of-conduct.md, _posts/2016-02-26-followup-open-code-of-conduct.md
Update status on the open code of conduct and future work
=> Update status on the open code of conduct

_posts/2016-03-29-open-source-program-management-tools.md
For @caniszczyk to be reviewed. Updated Bitergia toolkits info with updated info about GrimoireLab
=> Updated Bitergia toolkits info with GrimoireLab

_posts/2016-03-30-todo-becomes-lf-collaborative-project.md
Add post discussing evolving into an LF Collaborative Project.
=> Add blog post about becoming a LF collab project

_posts/2016-05-16-todo-at-oscon.md
Add blog post about TODO at OSCON + Nithya's interview at Linux.com recently.
=> Add post about TODO at OSCON 2016

_posts/2016-05-18-oscon-talk.md
http://conferences.oreilly.com/oscon/open-source-us/public/schedule/detail/49069
=> Add OSCON 2016 talk blog post

_posts/2016-05-18-oscon-talk.md
I just threw my notes together into a blog article in case folks are interested in the "transcript" of what I said.
=> Add a link to the blog article that I wrote

_posts/2016-05-19-sample-job-req.md, _posts/2016-05-25-sample-job-req.md
For anyone interested, this got a 93 on https://textio.com/talent/ #communicatebetter
=> A template job post

_posts/2016-07-19-linuxcon-japan-keynote.md
http://www.slideshare.net/gyehuda/rise-of-the-open-source-program-office-for-linuxcon-2016
=> Add Gil's keynote from LinuxCon Japan 2016

_posts/2016-09-13-atscale-panel.md
https://www.facebook.com/atscaleevents/videos/1775935579346205/
=> Add blog post about @Scale panel

members.md
=> Remove Amazon

_posts/2016-11-29-oslc-tahoe.md
http://events.linuxfoundation.org/events/open-source-leadership-summit
=> Add blog post about CFP for OSLC 2017

_posts/2017-03-21-todo-osls.md
List over some of the presentations from OSLS!
http://events.linuxfoundation.org/events/open-source-leadership-summit
=> Add OSLS summary blog post

_config.yml, _posts/2017-09-11-open-source-guides.md, guides.md
https://github.com/todogroup/guides
=> New blog post on open source program guides

_posts/2017-10-09-open-source-case-studies-fb.md
https://github.com/todogroup/guides/blob/master/casestudies/facebook.md
=> Add Facebook case study

_posts/2017-11-13-open-source-case-studies-autodesk.md
https://github.com/todogroup/guides/blob/master/casestudies/autodesk.md
=> Add Autodesk case study blog post

_posts/2017-12-20-open-source-case-studies-dropbox.md
https://opensource.dropbox.com/
=> Add dropbox case study

_posts/2018-02-22-opening-up-slack.md
=> Add blog on opening up Slack

_posts/2018-05-03-building-leadership.md
https://github.com/todogroup/guides/blob/master/building-leadership-in-an-open-source-community.md
=> Add building leadership blog post

faq.md
=> very minor change

content/blog/survey-2018.md
See: https://gohugo.io/content-management/summaries/
=> Fix summary of 2018 survey result blog post

data/companies.yaml, static/img/logo_didi.svg
=> Add Didi as a member

content/guides/create-program.md
This pr adds the contribution of open source and the creation of
open source to the list of topics to discuss in an open source
policy.
=> Adding contribution and open source creation to the policy topics

content/guides/strategy.md
- Correction of some bullet lists
- Removal of missing link to a Black Duck blogpost
- Correction of some typos
=> Corrections to Open Source Strategy Guide

content/en/guides/strategy.md
Updates the link on the Strategy guide page.
Resolves #90.
=> update Future of Open Source survey links

content/en/guides/starting.md
Signed-off-by: Gergely Csatari <gergely.csatari@nokia.com>
=> Correcting a typo in Starting an open source project

content/en/guides/management-tools.md
Some updates to the Management Tools wp.
Signed-off-by: Gergely Csatari <gergely.csatari@nokia.com>
=> Management Tools updates

content/en/guides/using-open-source.md
Signed-off-by: Gergely Csatari <gergely.csatari@nokia.com>
=> Corrections to Using open source code

content/en/guides/using-open-source.md, layouts/guides/single.html
* Fixed dead link in Guides
* Removed duplicate sentences in Using Open Source Code
=> Fix dead link and syntax

content/en/guides/strategy.md
The words help you was repeated twice in the `Partner with other organizations` paragraph
This resolves #105
=> Remove duplicate words in strategy.md [EN]

data/authors.yaml
=> updated my company name

data/companies.yaml
previous site listed for Comcast does not exist
=> Update companies.yaml with Comcast OSS site

Makefile, layouts/index.atom.xml, netlify.toml
This PR enables drafts of content and future blog posts to be displayed in the preview build.
=> Update build commands

content/en/guides/_index.md, content/en/guides/marketing-open-source-projects.md
Add guide on how to market open source projects.
=> Add Marketing guide

content/en/blog/todo-europe19.md
=> Update blog post

content/en/blog/survey-2019.md
=> Add 2019 survey results blog

content/en/blog/todo-osls.md
=> Fix OSLS 2017 broken links

content/en/guides/management-tools.md
This patch contains just a minor formatting fix.
=> Align acknowledgement section to other pages

content/en/blog/open-source-case-studies-uber.md
Urls of the projects were not properly linked.
=> fix (blog) : fixed urls in Uber todogroups blog

content/en/faq.md
=> Removing Facebook due to inactivity

content/en/blog/survey-2020.md
https://github.com/todogroup/survey/tree/master/2020
=> Add 2020 OSPO Survey Blog Post

content/en/blog/ospo-definition.md
https://github.com/todogroup/ospodefinition.org
=> Add OSPO Definition Blog

content/en/join.md
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
=> Change to AutoJoin link

content/en/guides/diversity-inclusion.md
This is one of the guides that has been in queue for awhile, had some time to clean it up during our last TODO get together.
=> Add diversity and inclusion guide

i18n/en.yaml
=> Update language to reflect reality

content/en/blog/ospo101.md
https://github.com/todogroup/ospo101
=> Add OSPO 101 blog

content/en/guides/management-tools.md
Made a note at the end that organizational affiliation is from 2019. 
Deleted all the projects that are from 2019.
=> Fixed bad links

content/en/blog/announcing-ospo-survey-2021.md
* Take Survey (EN): https://linuxfoundation.surveymonkey.com/r/OSPO21
* Take Survey (調査): https://linuxfoundation.surveymonkey.com/r/OSPO21?lang=ja
* Take Survey (民意调查): https://linuxfoundation.surveymonkey.com/r/OSPO21?lang=zh
=> Add blog on OSPO Survey 2021

content/en/guides/casestudies/rit.md
https://www.rit.edu/research/open
=> Add RIT academic OSPO case study

content/en/guides/casestudies/_index.md
=> Add RIT case study link

layouts/shortcodes/companiesList.html
This commit updates member page to pull from OSPO landscape
=> embed ospolandscape todo logos for members page

content/en/guides/marketing-open-source-projects.md
I've added information and a link to an article about using SEO for marketing in Search Engines and a link to an article with more information.
=> add info about using SEO for marketing Open Source projects

content/en/about.md, layouts/shortcodes/aboutTodo.html
This commit adds a google slide presentation within the todo website
=> add todo presentation

assets/scss/style.scss, layouts/index.html
This commit adds the OSPO landscape responsive image at todogroup.org website
=> add embed OSPO landscape and responsive image

content/en/guides/_index.md, content/en/guides/career-development.md
This commit adds career guide post
=> add career guide post

content/en/guides/os-commercial-ecosystem.md
- Normalize headings (start at H2 for headings after the title).
- Remove extraneous newlines and standarize markdown syntax.
- Use blockquotes rather than italicized paragraphs.
- Minor phrasing updates.
Closes todogroup/work-day-activities#20, Closes #227
=> Update Commercial Ecosystem guide

content/en/community.md
2022 Steering Committee:
- Ashley Wolf - @ashleywolf, GitHub
- Dawn Foster - @geekygirldawn, VMware
- Shilla Saebi - @shillasaebi, Comcast
- Stephen Augustus - @justaugustus, Cisco
- Stephen Jacobs - @itprofjacobs, RIT
- Thomas Steenbergen - @tsteenbe, HERE Technologies
- VM (Vicky) Brasseur - @vmbrasseur, Wipro
Signed-off-by: Stephen Augustus <foo@auggie.dev>
Thank you, @caniszczyk, @duaneobrien, @stormypeters, @kpfleming!
cc: @anajsana 
ref: https://github.com/todogroup/governance/issues/151
=> steering: Reflect results of 2021 election

content/en/blog/todo-steering-committee-2022.md
Follow-up to https://github.com/todogroup/todogroup.org/pull/270 to reflect the publish/merge date of the 2022 SC blog post.
Signed-off-by: Stephen Augustus <foo@auggie.dev>
=> blog: Reflect publish date for 2022 SC post

content/en/guides/management-tools.md
Adding under Source code scanning & license compliance section
=> Add Vigiles to management tools

content/en/join.md
document that the TODO community is open to all and is for those OSPOs that wishes to support TODO as General Member
=> update join info

content/en/community.md
Reverts todogroup/todogroup.org#297
=> Revert "Update community.md"

content/en/blog/convince-manager-start-ospo.md
My surname had a capital R instead of lowercase. Sorry
=> Update my surname convince-manager-start-ospo.md

content/en/community.md, layouts/shortcodes/calendar.html
improve calendar accessibility and view for the community page
=> improve calendar accessibility and view

content/en/guides/create-program.md
I updated GSOC details to show not just students are eligible for GSOC.
=> Updated GSOC information

content/en/blog/ospo-mind-map-2-release.md
=> create blog post announcing ospo mind map release

content/en/blog/todo-steering-committee-2022.md, content/en/community.md
Signed-off-by: Thomas Steenbergen <thomas_steenbergen@epam.com>
=> Update bio of Thomas Steenbergen

content/en/faq.md
Signed-off-by: Tristan <WindfallProphet@users.noreply.github.com>
=> faq suggestions

content/en/guides/_index.md
=> add ospo mind map japanese version link

content/en/associates.md
Fix typos and add some minor suggestions to the text
=> Hunting typos

content/en/guides/_index.md
=> add new ospo report link

content/en/guides/_index.md, content/en/guides/outbound-oss.md
This PR adds the content and creatives within the outbound-oss repo: https://github.com/todogroup/outbound-oss
=> Create initial PR for outbound oss guide

content/en/guides/outbound-oss.md
=> change pdf v3 for v4

content/en/guides/outbound-oss.md
=> add repo link for contributions

content/en/guides/outbound-oss.md
=> update pdf doc

config.yaml
Closes #351 
Signed-off-by: VM Brasseur <github@vmbrasseur.com>
=> Add link to Code of Conduct

content/en/guides/whitepaper-guidelines.md
small typo fix
Signed-off-by: Brian Fox <brianf@sonatype.com>
=> Typo in guidelines

content/en/guides/_index.md
- Add Chinese link of the evolution os of OSPO (from LFAPAC Yidaoshi SIG ) 
- Add Chinese link of OSPO mindmap
=> add Chinese links

content/en/blog/ospo-survey-2023.md
=> Update ospo-survey-2023.md links of Chinese and Japanese

content/en/guides/create-program.md
This pull request updates the link to the microsoft open source program webpage. The current link in the code results in a 404 error.
=> docs: msft ospo link

config/_default/languages.yaml, config/_default/params.yaml, content/en/blog/opening-up-slack.md, content/en/get-started.md, layouts/shortcodes/todo_guidebook.html, layouts/shortcodes/todo_presentation.html
New features in the updated theme [listed here](https://github.com/cncf/dot-org-hugo-theme/releases/tag/v0.1.2).
Closes #318
=> Update theme to v0.1.3

content/zh-CN/join.md, i18n/zh-cn.yaml
=> Update Chinese version pages 

content/zh-CN/glossary.md, content/zh-CN/mindmap.md, content/zh-CN/studies.md
=> Add translation pages in Chinese

config/_default/languages.yaml, content/en/osponews.md, layouts/shortcodes/todo_newsletter_form.html
[Described in this issue](https://github.com/todogroup/todogroup.org/issues/422)
=> Added newsletter page (#422)

content/en/guides/employee-engagement.md
This pull request supersedes #384. It incorporates the comments from the last call of the group working on the guide. It's still a draft. Further comments and refinements are welcome.
=> Employee Open Source Engagement Guide

content/en/blog/2024-ospo-survey-cfs.md
=> Create OSPO Survey CFS announcement

content/en/blog/welcome-new-generalmember.md
This is a WIP PR that needs further review from CAICT representatives and work on a Chinese translation.
Update: approved by CAICT representatives
* [Watch markdown deploy preview](https://github.com/todogroup/todogroup.org/blob/dd06b354b8a77736fb85956e781e67ecaa23035a/content/en/blog/welcome-new-generalmember.md)
* Watch the [website deploy preview](https://deploy-preview-429--todogroup.netlify.app/blog/welcome-new-generalmember/)
=> Create CAICT joins as TODO GM announcement

content/en/blog/cases-porsche-sony-ospo-book.md
New Use Cases Available in the OSPO Book: Porsche and Sony
=> [Blog] New Use Cases Available in the OSPO Book: Porsche and Sony

content/en/faq/university.md
=> Fix URL for UCSC in university.md

content/en/guides/employee-engagement.md
=> Fix markdown

content/en/meetings.md, layouts/shortcodes/todo_community_calendar.html, layouts/shortcodes/todo_community_calendars.html
create community calendar to differentiate the other calendars vs todo
=> create todo community calendar iframe shortcode

README.md, run-hugo-in-docker.sh, run-hugo.sh
This PR adds scripts to run hugo in docker.
Also, fix some nits.
=> Hugo in docker

content/en/guides/create-program.md
Fixed a broken link. 
Corrected link URL: https://todogroup.org/resources/guides/participating-in-open-source-communities/
=> Update create-program.md (link URL fixed)

content/ja/glossary.md
=> translate glossay into Japanese

i18n/ja.yaml
remove an extra ".
This modification will allow English slides to be displayed. Please let me know if you have any slides in Japanese.
=> fix link to the slide

content/en/ambassadors.md
Approved by TODO Steering Committee in [1].
[1]: https://github.com/todogroup/governance/issues/350
=> Add Thomas Steenbergen as TODO Ambassador

content/en/ambassadors.md
See individual commits for details.
=> Improve ambassador page

content/en/blog/End-of-Year-2024.md
add missing links and fix image resolution
=> mising links and fix image resolution End-of-Year-2024.md

content/en/blog/sc-q1-report.md
Fix surname `Barnawal` -> `Baranwal`
=> chore(sc-q1-report): fix surname

config/_default/languages.yaml, content/en/book.md
This PR adds the OSPO Book to the website's Nav Bar, where the book intro is written. It also deploys the OSPO Book website and provides a way to contribute to it.
=> chore(navbar): add ospobook

content/en/guides/management-tools.md
=> Add Vulert in the tool list

content/en/book.md
This PR adds a button to the book page for letting users download the PDF version
Preview:
=> chore(book.md): add Book PDF link

content/zh-CN/guides/management-tools.md
Add Vulert in the tool list ( zh-CN )
=> Add Vulert in the tool list ( zh-CN )
