todogroup/todogroup.org

guides.md

The link is currently not clickable on the website.

Make GitHub link clickable

---

members.md

Replacing link to deprecated blog on `/members` page for Salesforce

Update /members link for Salesforce

---

content/en/guides/management-tools.md

This change removes the mention of a "Open Source Program Office in A Box"
from the managing open source programs whitepaper.

Fix for bug #94

---

content/en/guides/create-program.md

This change adds the correct link to `Open Source Compliance in the Enterprise`
in every occurence.

Fix for bug #86

---

assets/scss/style.scss

I recently printed out one of the guides for offline reading, and found that a number of lines got cut off due to the footer being printed on every page. I also ended up with an arguably excessive number of pages, due to the double-spaced lines, and large font size. (These same issues exist when "printing" to PDF.)
This introduces a small bit of print-specific CSS to fix both of those issues.
Before:
After:
Notice, no more footer displayed, and the page count is cut in half!

Fix print styling

---

content/en/guides/casestudies/ni.md

With the comma in place it suggests that Linus's adoption of a change (something he does basically all the time) signaled the acceptance of the RT patch. Remove the comma to make it clear that his adoption of this specific change is what matters.
Also change end of file to what GitHub's in-browser editor prefers.

Fix misplaced comma

---

content/en/guides/management-tools.md

This commit adds FOSSID to the management tools, under license scanning.  FOSSID
is a commercial license and vulnerability scanning tool which uses snippet scans
to detect copied/pasted code, or code with insufficient license declarations.
Signed-off-by: Brian Warner <brian@bdwarner.com>

Add FOSSID to management tools

---

content/en/guides/casestudies/uber.md

The links in the intro on https://todogroup.org/guides/casestudies/uber/ were utterly broken, a big button on the page invited to come to github and fix it :-)
it seems the renderer on the main page is challenged by empty `[ ](...)` links 
- removed duplicate link to kepler.gl, cleaned up the others.
- cleaned up some more links further down in the document

casestudies/uber.md: fix links in intro

---

static/img/logo_xilinx.svg

fixes the immediate accessibility issue mentioned in #175, but not the broader question of poorly sized logos in general.

use black text for Xilinx logo

---

data/companies.yaml

The Khan Academy link is not IBM.

fix: Add correct Khan Academy link

---

README.md

There is no clear process where the TODO Community can contribute to OSPO use cases and/or TODO guides. This commit works as a first iteration to document a clear process for both resources and ease community contribution.

Add contributing guidelines for website resources

---

content/en/guides/_index.md

The TODO guides page shows more resources in addition to the TODO guides. I've added the different existing resources in the description section (_index.md)

add more todo resources to the todo guides description

---

i18n/en.yaml

I hope this message, along with the content in the [community page](https://todogroup.org/community/),  let others know that:
* It's not just for private orgs
* It is focused on OSPO and open source initiatives (added these keywords)
* Everyone can join the community and is not excluding practitioners to contribute to TODO

refresh todogroup.org description

---

content/en/community.md

This commit clarifies the community structure at TODO and highlights the OSPOlogy brand for community purposes

clarify community structure

---

netlify.toml

This Pull Request upgrades the Hugo version from 0.64.0 to v0.111.3, which has been resolved todogroup/todogroup.org#374.

build(hugo): upgrade hugo version into v0.111.3

---

content/en/blog/a-year-in-review-2022.md
content/en/blog/how-can-ospo-accelerate-innovation-and-digital-transformation.md
content/en/blog/new-member-goldman-sachs.md
content/en/blog/open-source-program-management-tools.md
layouts/_default/rss.xml

I've implemented a custom RSS feed to fix the issue that was experience by Chrome users when clicking directly on the RSS feed link  - #401 
`This page contains the following errors:
error on line 4 at column 868: Entity 'rsquo' not defined`
Note:
- The RSS Feed works if loaded in to RSS Viewer / Feedly / any RSS reader directly
- Safari does not display error
- Chrome displays error
The custom feed shows blog posts only. It implements some custom find and replace to remove some HTML entities that were being flagged by XML Validator. There may be a better approach or a "Hugo" way of doing this, but I couldn't find it.
The feed is now a "valid" RSS feed and the error has gone from Chrome.

Custom RSS feed

---

content/en/blog/2024-steering-committee.md

This PR fixes a small typo where it should state *2024* instead of *2023*.

Fix typo 2023 -> 2024

---

content/en/charter.md

broken url for Cornell voting link. it was adding the ) to the url which made it a Not Found

Update Cornell voting link in charter.md

---

content/en/guides/employee-engagement.md

As per our last meeting, I have edited the page a bit to make it flow a bit more. 
Signed-off-by: Alice Sowerby <acsowerby@hotmail.com>

Copy edits to get the page ready for publishing

---

content/en/meetings.md

Link to file where the guide is located in repo instead of the old pull request

Fix link to employee engagement guide

---

layouts/shortcodes/todo_associates.html
layouts/shortcodes/todo_group_members.html

[OSPO Landscape has migrated to a new view](https://github.com/todogroup/ospolandscape/issues/193) and now the url for iframes follows a different structure. Before the DNS switch available at: https://ospo.landscape2.io/embed-setup, after at https://landscape.todogroup.org/embed-setup
This PR updates the iframe embed url so the member organizations can be seen

Update iframe embed url for landscape view at todo website

---

i18n/zh-cn.yaml
layouts/index.html

This makes the buttons on the homepage point to the subpages in the same language.
This fixes #453.

Internationalize the links on the homepage to point to appropriate subpages

---

README.md
config/_default/languages.yaml
layouts/partials/breadcrumb.html
netlify.toml
package-lock.json
package.json

- Update all packages, upgrade to latest Hugo for Netlify build
- Fix change to languages params for new version of Hugo
- Add theme update instructions to readme
- Fix typo in readme
- Updated submodule to the latest version of dot-org-hugo-theme
- Added update notes to the readme
- Switched out the custom breadcrumbs for the themes own (as the component now works on different types)
- #398 updating the copyright message
Preview: https://deploy-preview-472--todogroup.netlify.app

Theme update

---

content/en/osponews.md

Adds the remaining newsletter to the newsletter archive so that people can see newsletters from 31 to 37 editions on the website.

chore(osponews): add remaining newsletter to archive

---

content/en/associates.md
content/zh-CN/associates.md

**Where can I find more info?** heading of [Associates](https://todogroup.org/about/associates/) links to a non-working link for TODO Guides and Resources link, which links to https://todogroup.org/about/associates/todogroup.org/guides, which is 404; it should have been https://todogroup.org/resources/guides/ instead.
Solves https://github.com/todogroup/todogroup.org/issues/538

chore(associates): fix link to `Guides and Resources page`

---

content/en/studies/structure.md

Fixes A Deep Dive into Open Source Program Offices report link. 
Earlier, it was giving 404 as the URL was `https://www.linuxfoundation.org/toolsa-deep-dive-into-open-source-program-offices/`
The correct link is `https://www.linuxfoundation.org/tools/a-deep-dive-into-open-source-program-offices/`

chore(studies): fix ospo structure report link

---

content/en/blog/ambassador-alin.md

Corrects Ambassador link. 
It was https://todogroup.org/ambassadors/, which is incorrect.
https://todogroup.org/community/ambassadors/ is the correct link

ambassador-alin.md: correct ambassador link

---

content/ja/guides/management-tools.md

[こちらのコメント](https://github.com/todogroup/todogroup.org/pull/530#discussion_r2030735036)に基づき、古い情報を削除しました。
Based on [this comment](https://github.com/todogroup/todogroup.org/pull/530#discussion_r2030735036), I removed the old information.

Delete an outdated information in Japanese guide
